---
name: "Connect ESPHome Device via ESPHome native API"
version: "1.0"
slug: "connect_esphome_device"
description: "Connect ESPHome Device via ESPHome native API"
startup: "application"
integration: "esphome"
boot: "auto"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
options:
  IP_DEVICE: "your_api_token_here"
  PASSOWRD: "your_password_here"
  ENCRYPTION_KEY: "your_encryption_key_here
  PORT: "your_port_here"
schema:
  IP_DEVICE: str
  PASSOWRD: str
  ENCRYPTION_KEY: str
